### ISSUE TITLE
Using '~' in the binarypath argument doesn't work correctly.

### ISSUE THREAD

**Issue by shanep2300** [browserstack/browserstack-local-nodejs#28]
Trying to make the path point inside the project folder so I try to use:
'~/binaries/BrowserStackLocal.exe'

The test fails and says there is not such directory found in:
'C:/Users/<user>/Documents/<project folder>/~/binaries/BrowserStackLocal.exe'

Using version 1.3.0 on Windows 7.

**Comment by pulkitsharma07** [comment]
Hi, node has issues using `~` in paths. Have a look here https://github.com/nodejs/node/issues/684.
As mentioned you can use `os.homedir()`.

**Comment by shanep2300** [comment]
Hmm, I'm getting the same issue where it adds the home directory correctly but os.homedir() is still found inside the path: 

`Error: ENOENT: no such file or directory, unlink 'C:\Users\<user>\Documents\<project>\os.homedir()\binaries\BrowserStackLocal.exe'`

**Comment by pulkitsharma07** [comment]
it seems like you are passing the `os.homedir()` inside the path, you need to call that method and add the value it returns in your path. I hope this is clear.
This code snippet should help.
```javascript
 console.log(os.homedir());
 var binary_path = os.homedir() + "\\binaries\\BrowserStackLocal.exe";
 console.log(binary_path);
``` 
You can run the above code snippet using `node` to see if it prints the desired information.

**Comment by shanep2300** [comment]
Perfect! Thank you very much!

**Comment by shanep2300** [comment]
Update fix:

`var path = require('path');`
`'binarypath': path.resolve(process.cwd()) +'/binaries/BrowserStackLocal.exe'`

This, gives the working directory as `os.homedir()` points to `C:\`, in my instance, which ultimately I wanted to avoid using if test is used on different machines.
