### ISSUE TITLE
Support passing enable-logging-for-api to BrowserstackBinary

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [browserstack/browserstack-local-nodejs#46]
Currently, there's no way to pass enable-logging-for-api to the BrowserstackBinary. It would be nice if I could.

**EDIT**  I may have prematurely filed this issue, not understanding that any unknown options are simply passed through.  Testing that now, and if so, I'll close the issue.  Thanks!

**Comment by tomthedev** [comment]
I can confirm this works. 

Adding in `'enable-logging-for-api' : ''`

Is passed straight to the local binary. 

Confirm both in windows process explorer : 

![image](https://user-images.githubusercontent.com/28949508/78831038-e2078400-79e0-11ea-812f-cad8de5705a4.png)

and when querying the local API : https://www.browserstack.com/local/v1/list?auth_token=ACCESS_KEY&last=5&state=running

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks for confirming @tomthedev.  Closing issue.
