### ISSUE TITLE
Don't kill connection when .pause() is used

### ISSUE THREAD

**Issue by openjck** [browserstack/browserstack-local-nodejs#58]
It looks like browserstack-local kills the connection to BrowserStack, skipping any remaining tests, when the [`.pause()` method](http://nightwatchjs.org/api/pause.html) is used for too long. The connection should be kept alive and tests should continue running when `.pause()` is used.

**Comment by openjck** [comment]
Apologies if I'm mistaken, and if this is instead something BrowserStack itself is doing.

**Comment by raghuhit** [comment]
@openjck , there is an idle timeout set by browserstack due to which you can't pause your sessions for too long. Default value of this timeout is 90 seconds, however you can increase it upto maximum value of 300 seconds by adding "browserstack.idleTimeout" capability.

**Comment by openjck** [comment]
Gotcha. It may have been something else, then. I actually can't reproduce it right now in a second repo. Sorry for the false alarm.
