### ISSUE TITLE
Please Support Local Binary v7.3

### ISSUE THREAD

**Issue by dstepper** [browserstack/browserstack-local-nodejs#60]
browserstack-local-nodejs 1.3.4 brings browserstack-local binary v7.2
Because of performance optimizations in the newest binary release, I need the last version 7.3. 

## Expected Behavior
browserstack-local-nodejs 1.3.4 brings browserstack-local binary v7.3

## Actual Behavior
browserstack-local-nodejs 1.3.4 brings browserstack-local binary v7.2

## Steps to Reproduce the Problem

  1. Open LocalBinary.js
  2. Copy your appropriated download location (eg linux 64 https://s3.amazonaws.com/browserStack/browserstack-local/BrowserStackLocal-linux-x64)
  3. Do wget on url
  4. check the version: ./BrowserStackLocal-linux-x64 -V
 
  1. browserstack-local-nodejs version: 1.3.4
  2. node version: 8.11.3
  3. os type and version: Ubuntu 16.04 LTS

**Comment by ray-pankaj** [comment]
Fixed in [v1.3.5](https://github.com/browserstack/browserstack-local-nodejs/releases/tag/v1.3.5). Closing.

**Comment by dstepper** [comment]
### 👍 thanks
