### ISSUE TITLE
Security issue in ps-tree dependency

### ISSUE THREAD

**Issue by cuongluu8** [browserstack/browserstack-local-nodejs#64]
There's a security vulnerability in `event-stream`, which is used by `ps-tree`.
More details here - https://github.com/indexzero/ps-tree/issues/33.  Not sure if `ps-tree` is still being maintained, so it might be a good idea to use an alternative library.

**Comment by punitx** [comment]
@cuongluu8 Thank you so much for giving us a heads up regarding the security issue. We have started working on a fix and will release the fix soon.

**Comment by raghuhit** [comment]
@cuongluu8 Thank you for raising this issue, for now we have removed the dependency of ps-tree and released a new version.

**Comment by indexzero** [comment]
FYI `ps-tree@1.1.1` locked to `event-stream@3.3.4` (which if I read the thread correctly pre-dates the questionable changes). 

Thanks to folks for bringing it to my attention: https://github.com/indexzero/ps-tree/pull/34

**Comment by zubhav** [comment]
Thanks for raising!

**Comment by raghuhit** [comment]
Released new version 1.3.7 which is locked to ps-tree's version 1.1.1
