### ISSUE TITLE
Add support for 7.4 HTTPS proxy

### ISSUE THREAD

**Issue by kpdecker** [browserstack/browserstack-local-nodejs#68]
https://www.browserstack.com/local-testing/releases/v7.4 adds support for https proxying. Would be awesome if support was added for consumers of the node lib.

**Comment by vedharish** [comment]
This library allows arbitrary key - value parameters to the `BrowserStackLocal` binary. [Check](https://github.com/browserstack/browserstack-local-nodejs/blob/230ec9357c95950c27dc5221324213a7525ec10d/lib/Local.js#L173-L178)

```node
bs_local.start({
  key: '<browserstack-accesskey>',
  'https-ports': '8443,9443'
}, function() {
  console.log("Started BrowserStackLocal");
});
```

should work

**Comment by kpdecker** [comment]
Cool. Does the binary in the S3 bucket need to be upgraded to 7.4 for that to work or should it be good to go?

**Comment by vedharish** [comment]
It should be fine. The s3 bucket links are an alternate to binary download links [here](https://www.browserstack.com/local-testing#command-line). Both always point to the latest version

**Comment by kpdecker** [comment]
Confirmed that it works after doing a rm on `~/.browserstack` Thanks!
