### ISSUE TITLE
Error: spawn ETXTBSY

### ISSUE THREAD

**Issue by adarshpala-hubdoc** [browserstack/browserstack-local-nodejs#82]
Issue: https://github.com/browserstack/browserstack-local-nodejs/issues/19
Error: spawn ETXTBSY 
    at _errnoException (util.js:1022:11) 
    at ChildProcess.spawn (internal/child_process.js:323:11) 
    at exports.spawn (child_process.js:502:9) 
    at Object.exports.execFile (child_process.js:212:15) 

I'm reopening this issue again because I'm seeing the same problem pop up in CI right now. This was the accepted solution that was merged into master:
https://github.com/browserstack/browserstack-local-nodejs/pull/23

The version of the dependancy is 1.3.7
The problem occurs when attempting to launch browserstack-local during an AWS CodeBuild run. It isn't consistently throwing an error though so there may still be a race condition which was mentioned in the original issue. 

The problem occurred in a container running Ubuntu 14.04.6 LTS.

**Comment by ckzgraphics** [comment]
Did you try updating to the [latest version 1.4.2](https://github.com/browserstack/browserstack-local-nodejs/releases/tag/v1.4.2) ?

Try this out and do share your findings.

**Comment by adarshpala-hubdoc** [comment]
Update on this issue: After several more CI builds have run the frequency of running into this problem seems to have increased if anything. Is there anything else that I could do to prevent this from happening?

**Comment by vedharish** [comment]
@adarshpala-hubdoc Please share the logs from this module. [Check|https://github.com/browserstack/browserstack-local-nodejs/blob/master/lib/LocalBinary.js#L28].

**Comment by adarshpala-hubdoc** [comment]
Thank you, the issue has been fixed. The problem was that the function to run test-cafe was not being called in the callback function supplied to the browserstack-local launch function. It was instead being called directly after which resulted in a race condition. This was fixed by calling test-cafe in the callback function.
