### ISSUE TITLE
Security vuln in https-proxy-agent

### ISSUE THREAD

**Issue by hindsc52** [browserstack/browserstack-local-nodejs#87]
Security vulnerability found `https-proxy-agent` which has been patched in v3.0.0.

https://www.npmjs.com/advisories/1184

**Comment by jiaoqiqi** [comment]
Same issue with me!!

**Comment by yashLadha** [comment]
This has been fixed in this [commit](https://github.com/browserstack/browserstack-local-nodejs/commit/61e371797b365f882b7516f245db62e39df1fc76) and changes are released. Thanks
